### ISSUE TITLE
Mypy crashes with AssertionError in sqlalchemy/ext/mypy/util.py

### ISSUE THREAD

**Issue by alexschoeberl** [sqlalchemy/sqlalchemy2-stubs#122] opened 2021-06-22 17:07 UTC
**Describe the bug**
Mypy outputs "Module service.models.Person is not valid as a type" and then crashes with the following traceback:

    version: 0.902
    Traceback (most recent call last):
      File "mypy/semanal.py", line 4872, in accept
      File "mypy/nodes.py", line 950, in accept
      File "mypy/semanal.py", line 1056, in visit_class_def
      File "mypy/semanal.py", line 1134, in analyze_class
      File "mypy/semanal.py", line 1143, in analyze_class_body_common
      File "mypy/semanal.py", line 1203, in apply_class_plugin_hooks
      File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/plugin.py", line 199, in _base_cls_hook
        decl_class._scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
      File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 90, in _scan_declarative_assignments_and_apply_types
        _scan_for_mapped_bases(cls, api, cls_metadata)
      File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 476, in _scan_for_mapped_bases
        _scan_declarative_assignments_and_apply_types(
      File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 90, in _scan_declarative_assignments_and_apply_types
        _scan_for_mapped_bases(cls, api, cls_metadata)
      File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 476, in _scan_for_mapped_bases
        _scan_declarative_assignments_and_apply_types(
      File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 51, in _scan_declarative_assignments_and_apply_types
        info = util._info_for_cls(cls, api)
      File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/util.py", line 211, in _info_for_cls
    assert sym and isinstance(sym.node, TypeInfo)
    AssertionError: 

`sym` seems to be None. Also, `Person` is a class, not a module. It is imported in __init__.py from person.py.
I am using from `__future__ import annotations` to avoid circular import issues when typing relationships in declarative models (they are in different files and reference each other).

**Expected behavior**
To not crash and to know that Person is a class.

**To Reproduce**
I am not sure how to reproduce it. It seems to happen only to one out of several similar models.

**Versions.**
 - OS: Linux Docker
 - Python: 3.8.10
 - SQLAlchemy: sqlalchemy[mypy]==1.4.18
 - mypy: 0.902

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-06-22 17:41
i believe this is a dupe of https://github.com/sqlalchemy/sqlalchemy/issues/6476

can you please try the SQLAlchemy master branch, as this fix is unreleased so far, and confirm it fixes your issue?  thanks

**Comment by alexschoeberl** [comment] 2021-06-22 18:11
Thanks! This solved the Assertion error. The other issue with "Module service.models.Person is not valid as a type" seems to be unrelated.

**Closed** 2021-06-22 18:12 UTC
Labels: awaiting info, duplicate
