### ISSUE TITLE
scoped_session is missing session attributes

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy2-stubs#139] opened 2021-07-29 09:42 UTC
**Describe the bug**
scoped_session can proxy to the underlying session, but these attributes are not present in the stubs. I'm not sure if we just want to copy them or have a mixin, therefore first this issue

**Expected behavior**
No error

**To Reproduce**
```py
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker

session_factory = sessionmaker(bind=create_engine("sqlite:////:memory:"))
scoped_session(session_factory).query
```

**Error**

```
x.py:6:1: error: "scoped_session" has no attribute "query"  [attr-defined]
    scoped_session(session_factory).query
```

**Versions.**
 - OS: Linux
 - Python: 3.7.1
 - SQLAlchemy: 1.4.22
 - mypy: 0.910
 - SQLAlchemy2-stubs: 0.0.2a6

**Comment by CaselIT** [comment] 2021-07-30 20:12
Hi,

this is a duplicate of #61. closing in favor of that one. Thanks for reporting in any case

**Closed by CaselIT** 2021-07-30 20:12 UTC
Labels: requires triage

**Comment by kasium** [comment] 2021-08-02 06:15
Thanks!
